'use strict';

var exports = {
    app: 'src/',
    dist: 'build/www/',
    scss: 'src/scss/',
    sassSrc: 'src/scss/**/*.{scss,sass}',
    cssDir: 'src/content/css',
    bower: 'src/bower_components/',
    tmp: 'build/tmp',
    uri: 'http://localhost:',
    languages: [
        'tr',
        'en'
    ],
    constantTemplate: '(function () {\n' +
    '    \'use strict\';\n' +
    '    // DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE\n' +
    '    angular\n' +
    '        .module(\'<%- moduleName %>\')\n' +
    '<% constants.forEach(function(constant) { %>        .constant(\'<%- constant.name %>\', <%= constant.value %>)\n<% }) %>;\n' +
    '})();\n',
    jsOrder: [
        '**/AppModule.js',
        '**/*Module.js',
        '**/*Constants.js',
        '**/*Provider.js',
        '**/AppConfig.js',
        '**/*Config.js',
        '**/AppRoute.js',
        '**/*Route.js',
        '**/*Service.js',
        '**/*Factory.js',
        '**/*Filter.js',
        '**/*Directive.js',
        '**/*Component.js',
        '**/*Interceptor.js',
        '**/*Handler.js',
        '**/*Controller.js',
        '**/*.js'
    ],
    vendorOrder: [
        '**/jquery.js',
        '**/moment.js',
        '**/angular.js',
        '**/angular-translate.js',
        '**/messageformat.js',
        '**/*angular-translate*.js',
        '**/*angular*.js',
        '**/highcharts.js',
        '**/rangy-core.js',
        '**/*.js'
    ]
};

exports.js = [
    exports.app + 'app/AppController.js',
    exports.app + 'app/**/!(*Spec).js'
];

module.exports = exports;

