(function () {
    'use strict';
    // DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE
    angular
        .module('app.blocks')
        .constant('VERSION', "2.0.0")
        .constant('DEBUG_INFO_ENABLED', true)
        .constant('API_URI', "https://test-autoflow.odc.com.tr/autoflow-api/rest")
;
})();
